spring:
  redis:
    host:localhost
    port:6379
    database:0
    password:000000
    timeout:6000

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/schema01
      username: root
      password: 123456
    news:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/simulation_1
      username: root
      password: 123456
    mycat:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:8066/simulation
      username: root
      password: 123456

